describe("pre test", function()
    it("should be able to load Parser", function()
    	stub(_G, "L")
    	stub(_G, "Misc")
    	stub(_G.Misc, "AddCallback")
    	stub(_G, "Turbine")
    	stub(_G.Turbine, "UI")
    	stub(_G.Turbine.UI, "Control", {parserControl = {}})

        assert.is.truthy(require('Parser'))
    end)
    it("should load constants", function()
        assert.is.truthy(require('Enums'))
    end)
end)